name: Inga analysis

on:
  pull_request:

jobs:
  inga-analysis:

    runs-on: ubuntu-latest
    container: ghcr.io/seachicken/inga:0.1.39-pre4-typescript

    steps:
    - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # https://github.com/actions/checkout/issues/124
        ref: ${{ github.event.pull_request.head.ref }}
    - run: inga --exclude "*.spec.ts" --min-combination 1 --github-token ${{ secrets.GITHUB_TOKEN }}
